---

# This playbook executes a backup script module on Windows hosts

- name: Run powershell script to backup vm
  hosts: all 
  gather_facts: false
  tasks:
    - name: Run powershell script
      script: D:\Veeam\Scripts\CloudForms-bkup.ps1
