---

# This playbook executes a backup script module on Windows hosts

- name: Run powershell script to backup vm
  hosts: all 
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Run powershell script
      script: D:\Veeam\Scripts\CloudForms-bkup.ps1
